### ISSUE TITLE
The "WPTT_CONTAINER_NAME" variable is not set

### ISSUE THREAD

**Issue by sanderdekroon** [valu-digital/wp-testing-tools#10]
Whenever I run `./docker/run compose` I get an error message telling me the WPTT_CONTAINER_NAME is not set.
```bash
WARN[0000] The "WPTT_CONTAINER_NAME" variable is not set. Defaulting to a blank string.
```

This is weird, as the `.env` file does contain it:
```
# Generated file. Do not edit. Edit .env.docker instead

# Assign unique name for the container
WPTT_CONTAINER_NAME=owcalgolia

# Where the testing installation will be made
WPTT_INSTALL_DIR=.wp-install
```
(I omitted the non-relevant lines).

Running the `config` command shows the same problem:
```bash
$ ./docker/run compose config

WARN[0000] The "WPTT_CONTAINER_NAME" variable is not set. Defaulting to a blank string.
WARN[0000] The "WPTT_CONTAINER_NAME" variable is not set. Defaulting to a blank string.
services:
  db:
    container_name: -db
    environment:
      DBGP_IDEKEY: wptt
      MYSQL_ROOT_PASSWORD: root
      WPTT_CONTAINER_NAME: owcalgolia
      WPTT_DB_HOST: db
      WPTT_DB_NAME: owcalgolia
      WPTT_DB_PASSWORD: root
      WPTT_DB_USER: root
      WPTT_INSTALL_DIR: .wp-install
      WPTT_SITE_ADMIN_EMAIL: admin@wp.test
      WPTT_SITE_ADMIN_PASSWORD: password
      WPTT_SITE_ADMIN_USERNAME: admin
      WPTT_SITE_HOST: localhost:8080
    env_file:
    - ../.env
    image: mariadb
    networks:
      default: null
```

Am I missing something here? According to the Docker docs this should work.

**Comment by noknokcody** [comment]
Can confirm I'm also getting the same error under the same conditions.

**Comment by esamattis** [comment]
It should be in the `.env.docker` file

See https://github.com/valu-digital/wp-graphql-polylang/blob/047847b01eb40eea6740196897fb566edf7cc9c3/.env.docker#L2

**Comment by sanderdekroon** [comment]
It is :). Just to be clear:

in `.env.docker`
```
# Assign unique name for the container
WPTT_CONTAINER_NAME=owcalgolia

# Where the testing installation will be made
WPTT_INSTALL_DIR=.wp-install
```

in `.env`
```
# Generated file. Do not edit. Edit .env.docker instead

# Assign unique name for the container
WPTT_CONTAINER_NAME=owcalgolia

# Where the testing installation will be made
WPTT_INSTALL_DIR=.wp-install
```

**Comment by sanderdekroon** [comment]
It also _should_ be in `.env.docker`, as its contents get copied over to `.env`. Something, somewhere isn't reading or applying the environment variables and I don't know why.

**Comment by noknokcody** [comment]
Okay, so I've done a little bit of testing. 

When I run ```./docker/run compose``` I get the following warning

``` bash
$ ./docker/run compose
WARNING: The WPTT_CONTAINER_NAME variable is not set. Defaulting to a blank string.
```

This is run using the following dockerfile.

``` yaml
version: "3.7"
services:
  wp:
    init: true
    env_file:
      - ../.env
    container_name: "${WPTT_CONTAINER_NAME}-wp"
    ports:
      - "8080:8080"
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
  db:
    container_name: "${WPTT_CONTAINER_NAME}-db"
    image: mariadb
    env_file:
      - ../.env
```

Hardcoding these variables seems to fix the issue and remove the warning. Docker isn't loading these via env_file for some reason.

I found I can revert my hardcoded changes and resolve this error by manually copying ./.env into ./docker/.env. 

I updated ./docker/run to write to./docker/.env automatically instead of ./.env. Then I updated docker-compose to use the new env_file location. 

Things are now running smoothly (minus some minimum PHP version errors I now have to work out).

This may be very much a hotfix, but here are the changes I made if you want a quick solution.

./docker/run
``` sh
#!/bin/sh

set -eu

cmd=docker/run
help() {
    echo "
    Docker shell wrapper for WP Testing Tools

    usage:


    $cmd compose [custom options]
        Start the Docker enviroment with docker-compose

    $cmd shell
        Enter the testing shell

    $cmd update
        Update these Docker scripts

    $cmd compose-no-init
        Start the container without installing anything. Usefull for
        debugging or developing install steps

    $cmd clean
        Remove the installation directory and containers

    "
}

if [ ! -f docker/run ]; then
    >&2 echo
    >&2 echo "Oops! The docker script is supposed to be run from the parent directory"
    >&2 echo "Ex. ./docker/run or more simply just docker/run"
    >&2 echo
    exit 1
fi

echo "# Generated file. Do not edit. Edit .env.docker instead" > ./docker/.env
echo "" >> ./docker/.env
cat .env.docker >> ./docker/.env
eval $(grep -v '^#' ./docker/.env)


shell() {
    command=$@

    if [ "$command" = "" ]; then
        command="bash -l"
        >&2 echo
        >&2 echo "Welcome to WordPress testing shell!"
        >&2 echo "Your plugin is mounted to /app and all composer dependencies are put to PATH."
        >&2 echo
        >&2 echo "Try: codecept run wpunit"
        >&2 echo " or: codecept run functional"
        >&2 echo
    fi

    exec docker exec -it "${WPTT_CONTAINER_NAME}-wp" $command
}

compose() {
    command=$@

    if [ "$command" = "" ]; then
        command="up --build --abort-on-container-exit"
    fi

    exec docker-compose -f docker/docker-compose.yml $command
}

update() {
    if [ -x ./vendor/bin/wptt-configure ]; then
        exec ./vendor/bin/wptt-configure --docker
    fi

    >&2 echo
    >&2 echo "valu/wp-testing-tools not installed with composer?"
    >&2 echo
    exit 5
}

clean() {
    rm -rf "$WPTT_INSTALL_DIR"
    compose rm
}

case "${1:-}" in
    -h|--help)
        help
        exit
    ;;
    "")
        >&2 help
        exit
    ;;
    compose)
        shift
        compose $@
    ;;
    compose-no-init)
        shift
        echo "WPTT_NO_INIT=1" >> ./docker/.env
        compose $@
    ;;
    shell)
        shift
        shell $@
    ;;
    update)
        shift
        update
    ;;
    clean)
        shift
        clean
    ;;
    *)
        >&2 echo "Bad action ${1:-}"
        exit 1
    ;;
esac
```

./docker/docker-compose
``` yml
version: "3.7"
services:
  wp:
    init: true
    env_file:
      - .env
    container_name: "${WPTT_CONTAINER_NAME}-wp"
    ports:
      - "8080:8080"
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
  db:
    container_name: "${WPTT_CONTAINER_NAME}-db"
    image: mariadb
    env_file:
      - .env

```
